# Define the app level settings

DROPBOX_ACCESS_TOKEN = "LADJrEFyvzAAAAAAAAAAPmxqPUmb_CQlDVK-iUvXLKyk6DbxuoV_0_UVoqTqZoIa"

ALGO_ACCESS_KEY = "simQAbMR5x/Aw1QuWcRenMEWffU1"

ALGO_EMOTION_API = "deeplearning/EmotionRecognitionCNNMBP/0.1.2"

WATSON_SPT_SERVICE_USERNAME = "a5278f53-f863-48bd-a634-1a246f4b62ba"
WATSON_SPT_SERVICE_PASSWORD = "SfNC1Zhyl5fG"

WATSON_TONE_SERVICE_USERNAME = "ebff9a33-1e3f-4af0-916e-b5f1f962d2a1"
WATSON_TONE_SERVICE_PASSWORD = "rQwXpYO54ijN"


SATORI_CHANNEL = "NWS-All-USA-Alerts"
SATORI_CHANNEL_API_ENDPOINT = "wss://open-data.api.satori.com"
SATORI_API_KEY = "DBC51f5a70D2dC4bfAE1CC4D6E7dbdC9"
